bundle agent example
{

  methods:
    "test" usebundle => test, action => now;

}

bundle agent test
{
  methods:
    "Report"
      usebundle => report_now($(this.bundle)),
      action => now;

    "Nested Report"
      usebundle => call_report_now,
      action => now;
}

bundle agent call_report_now
{
  methods:
    "Call Report"
      usebundle => report_now($(this.bundle)),
      action => now;
}
bundle agent report_now(caller)
{
  vars:
    first::
       "count" string => "first";
    second::
       "count" string => "second";
  reports:
    "Called from $(caller) ($(count))"
      action => now;
}

body action now
{
    ifelapsed => "0";
}
